"""SRT 解析与产物导出（纯函数层，无外部依赖）。"""

from __future__ import annotations

import re
from pathlib import Path

SRT_BLOCK_RE = re.compile(
    r"(\d+)\s*\n\s*([\d:,]+ --> [\d:,]+)\s*\n([\s\S]*?)(?=\n\s*\n|\Z)"
)

ASS_HEADER = """[Script Info]
; Script generated by Gemini subtitle workbench
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: 中文,微软雅黑,48,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,50,1
Style: 英文,Arial,36,&H0000FFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""


def _read_text(file_path: str | Path) -> str:
    """
    按字节读取再解码，避免 Windows 文本模式把 \\r\\n 二次转义成 \\r\\r\\n，
    导致读回来凭空多出空行（多行字幕被截断、块解析整体失效）。
    """
    raw = Path(file_path).read_bytes()
    content = raw.decode("utf-8-sig", errors="replace")
    # \r+\n 一起收敛为一个 \n，兼容被二次转义过的 \r\r\n
    return re.sub(r"\r+\n", "\n", content).replace("\r", "\n")


def parse_srt_text(content: str) -> list[dict]:
    """解析 SRT 文本（不依赖文件是否存在，供 log 内嵌字幕使用）。"""
    content = re.sub(r"\r+\n", "\n", content).replace("\r", "\n")

    subs: list[dict] = []
    for m in SRT_BLOCK_RE.finditer(content):
        subs.append(
            {
                "id": int(m.group(1)),
                "time": m.group(2).strip(),
                "text": m.group(3).strip(),
            }
        )
    return subs


def parse_srt(file_path: str | Path) -> list[dict]:
    """解析 SRT 文件 -> [{'id': int, 'time': str, 'text': str}, ...]"""
    return parse_srt_text(_read_text(file_path))


def srt_time_to_ass(time_str: str) -> str:
    """SRT 时间戳 00:00:00,490 -> ASS 时间戳 0:00:00.49"""
    normalized = str(time_str).strip().replace(",", ".")
    match = re.match(r"(\d+):(\d{2}):(\d{2})\.(\d+)", normalized)
    if not match:
        return "0:00:00.00"

    h, m, s, ms = match.groups()
    return f"{int(h)}:{m}:{s}.{(ms + '00')[:2]}"


def write_srt(
    file_path: str | Path,
    subtitles: list[dict],
    translations: dict[str, str],
) -> list[str]:
    """回写 SRT。缺失译文沿用原文，返回缺失的 id 列表。"""
    lines: list[str] = []
    missing: list[str] = []

    for sub in subtitles:
        sub_id = str(sub["id"])
        text = translations.get(sub_id)
        if text is None or not str(text).strip():
            text = sub["text"]
            missing.append(sub_id)
        lines.append(f"{sub_id}\n{sub['time']}\n{text}\n")

    Path(file_path).write_text("\n".join(lines), encoding="utf-8", newline="\n")
    return missing


def _parse_srt_blocks(file_path: str | Path) -> dict[str, dict]:
    """按块解析 -> {'1': {'start': ..., 'end': ..., 'text': ...}}"""
    return parse_blocks_text(_read_text(file_path))


def parse_blocks_text(content: str) -> dict[str, dict]:
    """按块解析 SRT 文本 -> {'1': {'start': ..., 'end': ..., 'text': ...}}"""
    data: dict[str, dict] = {}
    for block in re.split(r"\n\s*\n", content.strip()):
        lines = [ln.strip() for ln in block.splitlines() if ln.strip()]
        if len(lines) < 3 or not lines[0].isdigit():
            continue

        time_match = re.search(
            r"(\d{2}:\d{2}:\d{2}[,.]\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2}[,.]\d{3})",
            lines[1],
        )
        if not time_match:
            continue

        data[lines[0]] = {
            "start": srt_time_to_ass(time_match.group(1)),
            "end": srt_time_to_ass(time_match.group(2)),
            "text": " ".join(lines[2:]),
        }
    return data


def _ass_escape(text: str) -> str:
    return str(text).replace("\n", "\\N").replace("\r", "")


def build_ass(orig_srt_path: str | Path, trans_srt_path: str | Path) -> str:
    """合成双语 ASS 内容（英文在上、中文在下，沿用原时间轴）。"""
    orig = _parse_srt_blocks(orig_srt_path)
    trans = _parse_srt_blocks(trans_srt_path)
    return build_ass_from_blocks(orig, trans)


def build_ass_from_blocks(orig: dict[str, dict], trans: dict[str, dict]) -> str:
    dialogues: list[str] = []
    for idx in sorted(orig, key=lambda x: int(x)):
        item = orig[idx]
        start, end = item["start"], item["end"]
        dialogues.append(
            f"Dialogue: 0,{start},{end},英文,,0,0,0,,{_ass_escape(item['text'])}"
        )
        if idx in trans:
            dialogues.append(
                f"Dialogue: 0,{start},{end},中文,,0,0,0,,"
                f"{_ass_escape(trans[idx]['text'])}"
            )

    return ASS_HEADER + "\n".join(dialogues) + "\n"


def write_ass(
    orig_srt_path: str | Path,
    trans_srt_path: str | Path,
    output_ass_path: str | Path,
) -> Path:
    return write_ass_from_blocks(
        _parse_srt_blocks(orig_srt_path),
        _parse_srt_blocks(trans_srt_path),
        output_ass_path,
    )


def write_ass_from_blocks(
    orig: dict[str, dict],
    trans: dict[str, dict],
    output_ass_path: str | Path,
) -> Path:
    out = Path(output_ass_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build_ass_from_blocks(orig, trans), encoding="utf-8")
    return out


def blocks_from_subtitles(
    subtitles: list[dict], translations: dict[str, str] | None = None
) -> tuple[dict[str, dict], dict[str, dict]]:
    """由内存中的字幕列表直接构造双语 ASS 所需的原文块 / 译文块。

    字幕已内嵌进任务库，导出时不必依赖外部 srt 文件。
    """
    translations = translations or {}
    orig: dict[str, dict] = {}
    trans: dict[str, dict] = {}

    for sub in subtitles:
        sid = str(sub["id"])
        start, _, end = _split_time(sub["time"])
        text = " ".join(str(sub["text"]).splitlines())
        orig[sid] = {"start": start, "end": end, "text": text}

        value = translations.get(sid)
        if value is None or not str(value).strip():
            value = text
        trans[sid] = {"start": start, "end": end, "text": " ".join(str(value).splitlines())}

    return orig, trans


def _split_time(time_str: str) -> tuple[str, str, str]:
    """SRT 时间轴 '00:00:01,000 --> 00:00:03,000' -> (start_ass, '-->', end_ass)"""
    raw = str(time_str)
    parts = [p.strip() for p in raw.split("-->")]
    if len(parts) != 2:
        return "0:00:00.00", "-->", "0:00:00.00"
    return srt_time_to_ass(parts[0]), "-->", srt_time_to_ass(parts[1])
